apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftptd
  namespace: paas-shack
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ftptd
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ftptd
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: config
        - secretRef:
            name: secrets
        image: ghcr.io/paas-shack/ftp:main
        imagePullPolicy: Always
        name: ftptd
        ports:
        - name: port-21
          containerPort: 21
          protocol: TCP
        - name: port-45000
          containerPort: 45000
          protocol: TCP
        - name: port-45001
          containerPort: 45001
          protocol: TCP
        - name: port-45002
          containerPort: 45002
          protocol: TCP
        - name: port-45003
          containerPort: 45003
          protocol: TCP
        - name: port-45004
          containerPort: 45004
          protocol: TCP
        - name: port-45005
          containerPort: 45005
          protocol: TCP
        - name: port-45006
          containerPort: 45006
          protocol: TCP
        - name: port-45007
          containerPort: 45007
          protocol: TCP
        - name: port-45008
          containerPort: 45008
          protocol: TCP
        - name: port-45009
          containerPort: 45009 
        resources: {}
        env:
        - name: SERVICES
          value: services/**/*.agent.js
        envFrom:
        - configMapRef:
            name: config
        - secretRef:
            name: secrets
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
