apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftp
  namespace: paas-shack
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: ftp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ftp
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: config
        - secretRef:
            name: secrets
        image: ghcr.io/paas-shack/ftp@sha256:8cb98e4f2b5fd2c5f9a5e7c13c862519ee052691f1e60869e266dd731d9a1118 
        imagePullPolicy: Always
        name: ftp
        ports:
        - name: port-21
          containerPort: 21
          protocol: TCP
        - name: port-45000
          containerPort: 45000
          protocol: TCP
        - name: port-45001
          containerPort: 45001
          protocol: TCP
        - name: port-45002
          containerPort: 45002
          protocol: TCP
        - name: port-45003
          containerPort: 45003
          protocol: TCP
        - name: port-45004
          containerPort: 45004
          protocol: TCP
        - name: port-45005
          containerPort: 45005
          protocol: TCP
        - name: port-45006
          containerPort: 45006
          protocol: TCP
        - name: port-45007
          containerPort: 45007
          protocol: TCP
        - name: port-45008
          containerPort: 45008
          protocol: TCP
        - name: port-45009
          containerPort: 45009 
        resources: {}
        env:
        - name: SERVICES
          value: services/**/*.js
        envFrom:
        - configMapRef:
            name: config
        - secretRef:
            name: secrets
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: nfs-server-0
          mountPath: /mnt/nfs-0
        - name: nfs-server-1
          mountPath: /mnt/nfs-1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nfs-server-0
        nfs:
          server: "nfs-server-0.nfs-server.storage.svc.cloud.one-host.ca"
          path: "/"
      - name: nfs-server-1
        nfs:
          server: "nfs-server-1.nfs-server.storage.svc.cloud.one-host.ca"
          path: "/"
